services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false

databases:
  - name: expense-tracker-db
    databaseName: expense_tracker
    user: expense_user