"""new changes to db

Revision ID: 8e0c4ea473fe
Revises: 
Create Date: 2025-09-29 13:39:23.158454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0c4ea473fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('income_category_group_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('income_category_group_id_fkey'), 'group', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
