"""new changes to db

Revision ID: a7cda4a33931
Revises: 6479518a7e37
Create Date: 2025-09-29 13:55:20.059416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cda4a33931'
down_revision = '6479518a7e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_allocation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('income_allocation_income_entry_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('income_allocation_allocation_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'income_allocation_category', ['allocation_category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'income_entry', ['income_entry_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('income_entry', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('income_entry_group_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('income_entry_group_id_fkey'), 'group', ['group_id'], ['id'])

    with op.batch_alter_table('income_allocation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('income_allocation_allocation_category_id_fkey'), 'income_allocation_category', ['allocation_category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('income_allocation_income_entry_id_fkey'), 'income_entry', ['income_entry_id'], ['id'])

    # ### end Alembic commands ###
